### PR TITLE
Updated Makefile and preferences for iOS 8

### PR DESCRIPTION
**Pull request by apocolipse**

### CODE REVIEW

**Comment by bored-engineer** [comment]
Awesome work! Thanks. Do you have any interest in taking over the project? Obviously I haven't done much to work on it in the last few years and it's in need of a new maintainer.

**Comment by apocolipse** [comment]
Meh, I mostly just updated it because I use an external DAC for audio, that has horrible volume range (I use a separate inline amp), its range is effectively 60%-95% (under 60% total volume silent, over 95% clips), the default steps provide too large a difference in volume post-amp, so updated this to give me smaller steps :) (I actually downloaded it for a few months and just shrugged off it not working, stumbled upon your git last night).

If you'd like I can take it over, but I think it'll be pretty good going forward, it really just needed the arm64 update, the preferences updates were for smaller steps (for my given use case), and for "live preference updates" in iOS 8 (since iOS 8 preferences don't immediately write to file as previously)

**Comment by bored-engineer** [comment]
No worries. I'm fine with continue to run it. If you want to build a updated deb file I'd be happy to submit it to BigBoss though, since I don't even have a development environment setup anymore.

**Comment by apocolipse** [comment]
Uploaded to dropbox for you [com.innoying.volumestep_1.3.0-1_iphoneos-arm.deb](https://www.dropbox.com/s/h7ly6jrd9t34kon/com.innoying.volumestep_1.3.0-1_iphoneos-arm.deb?dl=0)

**Pull request merged**
